# Generated by Django 2.2.13 on 2021-11-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200910_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='self',
            field=models.TextField(default='None', max_length=300, verbose_name='О себе'),
        ),
    ]
