# Generated by Django 2.2.13 on 2021-11-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211119_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='git',
            field=models.URLField(default=1, max_length=100, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
