# Generated by Django 2.2.13 on 2021-11-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_git'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='git',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Ссылка'),
        ),
    ]
