# Generated by Django 2.2.13 on 2021-11-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211119_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('student', 'Студент'), ('private', 'Приватный')], default='student', max_length=15, verbose_name='Публичный'),
        ),
    ]
