# Generated by Django 2.2.13 on 2021-11-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('student', 'Студент'), ('private', 'Приватный')], default='student', max_length=15, null=True, verbose_name='Статус'),
        ),
    ]
