# Generated by Django 2.2.13 on 2021-11-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20211119_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.URLField(auto_created='https://t.me/joinchat/j5MzJfC5XQ00N2Yy', blank=True, null=True, verbose_name='Ссылка на глобальный чат'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('student', 'Студент'), ('university', 'Вуз'), ('company', 'Компания')], default='student', max_length=15, null=True, verbose_name='Статус'),
        ),
    ]
