# Generated by Django 2.2.13 on 2021-11-19 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0004_photo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jopenings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Оглавление')),
                ('description', models.CharField(blank=True, max_length=6000, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jopenings_album', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
