# Generated by Django 2.2.13 on 2021-11-19 21:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0005_jopenings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jopenings',
            new_name='Jopening',
        ),
    ]
